version: '3.8'

services:
  stacks-node:
    image: blockstack/stacks-blockchain:3.2.0.0.0-alpine
    container_name: stacks-node
    ports:
      - "20443:20443"  # RPC port
      - "20444:20444"  # P2P port
    volumes:
      - ./settings/Devnet.toml:/src/stacks-node/Config.toml
      - stacks-data:/src/stacks-node/data
    command: ["/bin/stacks-node", "start", "--config", "/src/stacks-node/Config.toml"]
    environment:
      - RUST_LOG=info
    networks:
      - stacks-network
    platform: linux/amd64

  postgres:
    image: postgres:15-alpine
    container_name: stacks-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stacks_blockchain_api
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - stacks-network

volumes:
  stacks-data:
  postgres-data:

networks:
  stacks-network:
    driver: bridge
